# Generated by Django 2.2.10 on 2020-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0004_auto_20200413_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Height',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Weight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
