# Generated by Django 2.2.10 on 2020-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0005_auto_20200413_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
